version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqleto
      MYSQL_DATABASE: topeducation
    ports:
      - 33060:3306
  app:
    container_name: preutopeducation
    image: letoesp/preutopeducation
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/TopEducation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysqleto
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db

